name: quoter
version: '2.5.5'
summary: Command line utility to pull stock and index quotes
description: |
  Quote fetches stock quotes and index data from IEXCloud.IO.
  You'll need a free private key from them to use it.  
  You can register and get one on iexcloud.io.
  http://github.com/frossm/quoter

grade: stable
confinement: strict
base: core18

# Enable faszter LZO compression
compression: lzo

apps:
   quoter:
      command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/quoter.jar

parts:
   library:
      plugin: maven
      source: https://github.com/frossm/library.git
      source-type: git
      source-tag: 'v2021.02.01'
      maven-options: [install]

   quoter:
      plugin: maven
      source: https://github.com/frossm/quoter.git
      source-branch: master
      source-type: git
      after: [library]

plugs:
   # Quoter requires network access to download quotes
   quoter-network:
      interface: network
