name: fquote
version: '2019.08.28'
summary: Command line utility to pull stock and index quotes
description: |
  Quote pulls stock quotes from IEXCloud.IO.  You'll need a private key
  to use it.  You can register and get one on iexcloud.io.
  http://github.com/frossm/quote

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict  # use 'strict' once you have the right plugs and slots
base: core18

apps:
  fquote:
    command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/quote.jar

parts:
  library:
    plugin: maven
    source: https://github.com/frossm/library.git
    source-tag: master
    source-type: git
    maven-options: [install]

  fquote:
    plugin: maven
    source: https://github.com/frossm/quote.git
    source-tag: master
    source-type: git
    after: [library]
