name: quoter
version: '3.0.0'
summary: Command line utility to pull stock and index quotes
description: |
  Quoter fetches stock quotes and index data for easy display on
  the command line.  Quote are obtained from IEXCloud.IO, and index
  information is scrapped from a financial website.
  To use IEXCloud, you'll need a free private key from them to use it.  
  You can register and get one on iexcloud.io.
  http://github.com/frossm/quoter

grade: stable
confinement: strict
base: core18

title: Quoter
website: https://github.com/frossm/quoter
contact: quoter@fross.org
issues: https://github.com/frossm/quoter/issues
icon: graphics/PostIt-512x512.png
license: MIT

# Enable faszter LZO compression
compression: lzo

apps:
   quoter:
      command: bin/java -Djava.util.prefs.userRoot="$SNAP_USER_DATA" -jar $SNAP/jar/quoter.jar

parts:
   library:
      plugin: maven
      source: https://github.com/frossm/library.git
      source-type: git
      source-tag: 'v2021.10.24'
      maven-options: [install]

   quoter:
      plugin: maven
      source: https://github.com/frossm/quoter.git
      source-branch: master
      source-type: git
      after: [library]
      override-prime: |
         snapcraftctl prime
         rm -vf usr/lib/jvm/java-11-openjdk-*/lib/security/blacklisted.certs

plugs:
   # Quoter requires network access to download quotes
   quoter-network:
      interface: network

